name: 'Puppeteer Headful'
description: 'Github Action for Puppeteer that can be ran "headful" or not headless.'
inputs:
  commands:
    description: 'Commands'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commands }}